### ISSUE TITLE
No support for apu2?

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/osfv-scripts#35]
```bash
% osfv_cli rte --rte_ip $RTE_IP serial
DUT model retrieved from snipeit: APU2
Traceback (most recent call last):
  File "/home/user/src/3mdeb/dasharo/open-firmware-rte/venv/bin/osfv_cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/src/3mdeb/dasharo/open-firmware-rte/osfv-scripts/osfv_cli/osfv_cli/osfv_cli.py", line 716, in main
    rte = RTE(args.rte_ip, dut_model_name, snipeit_api)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/3mdeb/dasharo/open-firmware-rte/osfv-scripts/osfv_cli/osfv_cli/rte.py", line 34, in __init__
    self.dut_data = self.load_model_data()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/3mdeb/dasharo/open-firmware-rte/osfv-scripts/osfv_cli/osfv_cli/rte.py", line 43, in load_model_data
    raise UnsupportedDUTModel(
osfv_cli.rte.UnsupportedDUTModel: The APU2 model is not yet supported
zsh: exit 1     osfv_cli rte --rte_ip $RTE_IP serial
```

**Comment by macpijan** [comment]
Please include tool version with the bug report. Should be there: https://github.com/Dasharo/osfv-scripts/tree/main/osfv_cli/osfv_cli/models

**Comment by pietrushnic** [comment]
```bash
% osfv_cli -v
0.3.1
```

**Comment by pietrushnic** [comment]
True on `v0.4.2` everything seem to work as expected.
